autoscaleEnabled: true
autoscaleMin: 2
autoscaleMax: 2

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: istiod
        topologyKey: kubernetes.io/hostname

global:
  proxy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: "1"
        memory: 512Mi

meshConfig:
  accessLogFile: /dev/stdout
  enableTracing: true
  defaultConfig:
    holdApplicationUntilProxyStarts: true
  enablePrometheusMerge: true
  extensionProviders:
    - name: otel-tracing
      opentelemetry:
        service: otel-collector.observability.svc.cluster.local
        port: 4317
        resource_detectors:
          environment: {}
