apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: platform-tracing
  namespace: platform
spec:
  tracing:
    - providers:
        - name: otel-tracing
      randomSamplingPercentage: 100
