apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mesh-security
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: ai-multicloud-k8s
spec:
  project: mesh-security
  source:
    repoURL: https://github.com/tejas-ae/AI-Multi-Cloud-K8s.git
    targetRevision: main
    path: gitops/mesh/policy
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
